version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: task-app-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passworddb
      POSTGRES_DB: task_app
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    # networks:
    # - taks-network

volumes:
  postgres_data:
# networks:
#   task-network:
